"""updated participants model

Revision ID: 31f9eeeb8cc2
Revises: 47b9d5d5dd50
Create Date: 2023-07-03 04:42:41.223190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f9eeeb8cc2'
down_revision = '47b9d5d5dd50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('elections', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
